### ISSUE TITLE
YSF2DMR Audio volume

### ISSUE THREAD

**Issue by oe1kbc** [juribeparada/MMDVM_CM#2]
audio volume from YSF to DMR is really ok but audio came from DMR is to much volume going to C4FM devices. Any help on this issue?
73 de Kurt
OE1KBC

**Comment by juribeparada** [comment]
Yes, I know that, I really want to solve this issue, but involves to modify the AMBE data packets, which for copyright issues is not possible to do with software, only with AMBE dongles. And I prefer to not use AMBE hardware for this software-only software. This also happens with other modes conversions (specially with NXDN), because unfortunately each mode uses different audio levels.
